// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9km7bsrhGeMLlgDaGyLg65ycUiu7fiM8',
    appId: '1:187818008009:android:36f681e1c96f640cd85c18',
    messagingSenderId: '187818008009',
    projectId: 'testbed-7750b',
    storageBucket: 'testbed-7750b.appspot.com',
  );

  ///TODO:
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5bXXy4M28qeyJDmpyiFutDF9syc08E9M',
    appId: '1:187818008009:ios:85446e5fc5ac93b63ee546',
    messagingSenderId: '187818008009',
    projectId: 'testbed-7750b',
    storageBucket: 'testbed-7750b.appspot.com',
    androidClientId:
        '151352305203-b7no5egb5107m05enpt88s1m17r1rnt4.apps.googleusercontent.com',
    iosClientId:
        '151352305203-ieov3v5h7ucc38hlij5t2ob308f6bevs.apps.googleusercontent.com',
    iosBundleId: 'com.example.ryan',
  );
}
